### ISSUE TITLE
Implement Shadowlisp's expand-path

### ISSUE THREAD

**Issue by burke** [Shopify/shadowenv#14]
It's [documented](https://shopify.github.io/shadowenv/shadowlisp/#expand-path) but in actuality it's just a stub currently.

`(expand-path "~/foo")` should be `"/Users/me/foo"`. I'd expect this to work approximately like `File.expand_path(x)` in ruby.

**Comment by paarthmadan** [comment]
I'll take this one :)

**Comment by burke** [comment]
Excellent, thanks!
