### ISSUE TITLE
Shadowenv takes the blame for invalid dev.yml

### ISSUE THREAD

**Issue by amooz** [Shopify/shadowenv#25]
If Shadowenv comes across an invalid dev.yml file, it tries to take the blame.  In the output below, you can see it ends with `This is a bug in dev or shadowenv.`, which isn't quite true.

Also, if possible, it would be great if shadownev would report which value was invalid.  

> ┏━━ There was an issue parsing your dev.yml's env section ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> ┃ must be a hash with keys and values all Strings
> ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.0s) ━━
> 𝒾 generate shadowenv for custom_env
> ┏━━ There was an issue parsing your dev.yml's env section ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> ┃ must be a hash with keys and values all Strings
> ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.0s) ━━
> ✗ generate shadowenv for custom_env: failed!
> ✗ Error Reason:
> ✗   Dev::Shadowenv::Dep::CannotBuild: dev.yml env was invalid
> ✗   /opt/dev/lib/dev/shadowenv/deps/custom_env.rb:43:in `validate'
> ✗   /opt/dev/lib/dev/shadowenv/deps/custom_env.rb:21:in `compile'
> ✗   /opt/dev/lib/dev/shadowenv/dep.rb:48:in `meet'
> ✗   /opt/dev/lib/dev/dep.rb:22:in `call'
> ✗   /opt/dev/lib/dev/task.rb:261:in `block (2 levels) in run_deps'
> ✗   /opt/dev/lib/dev/stats/statsd.rb:205:in `time'
> ✗   /opt/dev/lib/dev/task.rb:260:in `block in run_deps'
> ✗   /opt/dev/lib/dev/task.rb:244:in `each'
> ✗   /opt/dev/lib/dev/task.rb:244:in `with_index'
> ✗   /opt/dev/lib/dev/task.rb:244:in `run_deps'
> ✗   /opt/dev/lib/dev/task.rb:234:in `block in call_with_dir_set'
> ✗   /opt/dev/lib/dev/task/formatter.rb:36:in `phase'
> ✗   /opt/dev/lib/dev/task.rb:233:in `call_with_dir_set'
> ✗   /opt/dev/lib/dev/task.rb:187:in `block in call'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/util.rb:121:in `with_dir'
> ✗   /opt/dev/lib/dev/task.rb:186:in `call'
> ✗   /opt/dev/lib/dev/task_engine/executor.rb:34:in `block (2 levels) in do_execute'
> ✗   /opt/dev/lib/dev/stats/statsd.rb:205:in `time'
> ✗   /opt/dev/lib/dev/task_engine/executor.rb:33:in `block in do_execute'
> ✗   /opt/dev/lib/dev/task_engine/executor.rb:30:in `each'
> ✗   /opt/dev/lib/dev/task_engine/executor.rb:30:in `do_execute'
> ✗   /opt/dev/lib/dev/task_engine/executor.rb:12:in `block in execute!'
> ✗   /opt/dev/lib/dev/util.rb:78:in `timed'
> ✗   /opt/dev/lib/dev/task_engine/executor.rb:11:in `execute!'
> ✗   /opt/dev/lib/dev/commands/up.rb:40:in `block in run_locked'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/util.rb:121:in `with_dir'
> ✗   /opt/dev/lib/dev/commands/up.rb:39:in `run_locked'
> ✗   /opt/dev/lib/dev/commands/up.rb:33:in `block in call'
> ✗   /opt/dev/lib/dev/commands/up.rb:62:in `with_locks'
> ✗   /opt/dev/lib/dev/commands/up.rb:32:in `call'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/base_command.rb:24:in `block in call'
> ✗   /opt/dev/lib/dev/stats/statsd.rb:205:in `time'
> ✗   /opt/dev/lib/dev/command.rb:25:in `statsd_time'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/base_command.rb:23:in `call'
> ✗   /opt/dev/lib/dev/command.rb:13:in `call'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
> ✗   /opt/dev/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
> ✗   /opt/dev/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
> ✗   /opt/dev/lib/dev/entry_point.rb:19:in `call'
> ✗   /opt/dev/bin/dev:41:in `block in <main>'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:74:in `handle_abort'
> ✗   /opt/dev/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:20:in `call'
> ✗   /opt/dev/bin/dev:40:in `<main>'
> ✗   Failed to build shadowenv for custom_env.
> ✗   This is a bug in dev or shadowenv.
> 
> 🤷  generate shadowenv for custom_env: failed!

### Additional Context
Late this afternoon, Shadowenv started failing for members of the Shopify Fulfillment team.  Turns out, this was because we had a port value that was a number not a string.  We're unsure why this started failing, as this value has been the same for quite some time, and Shadowenv was enabled yesterday or the Friday before.  We were able to fix the root problem here https://github.com/Shopify/fbs/pull/3266, but shadowenv shouldn't try to take the blame if it's a problem with the config file.

**Comment by burke** [comment]
Just FYI, this is a public project. Totally fine to talk about `dev` and dev.yml here, just be cautious what you say about internal projects, etc.

I'll take a look tomorrow.
