### ISSUE TITLE
Don't output to stderr if running in non-interactive shell

### ISSUE THREAD

**Issue by exterm** [Shopify/shadowenv#27]
I have my atom `linter-rubocop` package configured to execute `/opt/dev/bin/shim bundle exec rubocop`, which has worked just fine until recently. Looking into the error log I see an error like

`[Linter] Error running RuboCop Error: [1;34mactivated [38;5;249ms[38;5;248mh[38;5;247ma[38;5;246md[38;5;245mo[38;5;244mw[38;5;243me[38;5;242mn[38;5;241mv[38;5;240m [1;34m(node:v8.12.0, ruby:2.5.3)[0m`

Which seems to just say that shadowenv is working fine, but it breaks the rubocop linter. It seems that it is running in a non-interactive shell so it should be easy to not print that status message in this situation.

**Comment by exterm** [comment]
I managed to work around it by directly referring to the rubocop executable, so working around shadowenv. That's not super good though as it really only works on a per project basis; the previous configuration, using shadowenv, could have worked with any dev-based project.

**Comment by exterm** [comment]
Meaning it breaks when switching between projects right now 😢

**Comment by exterm** [comment]
The underlying problem here is that in https://github.com/Shopify/shadowenv/blob/master/src/output.rs, we print to stderr also for success status messages, not just for errors. We should not do that if the shell we're running in is not interactive, IMO.

**Comment by lugray** [comment]
PRs are definitely welcome.

**Comment by exterm** [comment]
After talking to Lisa it seems that, from all the options I know, reading the environment variable `$PS1` which is apparently only set in interactive shells, via `std::env::var`, is the best option. I will take a stab at it soon

**Comment by exterm** [comment]
This is slightly embarrassing but I found that it is easier for me to hack bash than rust. This is a working workaround for now:
`/opt/dev/bin/shim bundle exec rubocop 2> >(tail -n +2 >&2)`

Cuts off the first line of the stderr output, which is the shadowenv line.

**Comment by burke** [comment]
If anyone wants to pick this up, probably https://github.com/softprops/atty would be a reasonable way to make this call programmatically.

**Comment by dantecatalfamo** [comment]
I'm having the same issue with this as well, I get my path from shell in emacs and it often comes back scrambled with escape characters from shadowenv

**Comment by paarthmadan** [comment]
Hey, I'm pretty new to rust, and Shopify, but I'd love to try taking on this task. I'm currently a DevDegree intern working on the arrive-team, but I'm learning rust on the side. Is this something that needs to be done urgently?

**Comment by lugray** [comment]
> Is this something that needs to be done urgently?

It is not.  Feel free to take a swing at it.
