### ISSUE TITLE
Shadowenv trust failure reported too often

### ISSUE THREAD

**Issue by lugray** [Shopify/shadowenv#4]
Tested in zsh.

When shadowenv is not trusted, it prints before and after commands run.  This means that we see the message twice.  It also means that when we actually run `shadowenv trust`, we see the message (once).  I suggest printing only after the command is run, solving both problems.

**Comment by sorryeh** [comment]
Deleted my issue, just noticed this one. Ditto

![image](https://user-images.githubusercontent.com/6529635/53102098-095b7300-34f9-11e9-923d-f7d2196ce787.png)

The error line seems  pretty spammy. Any chance it could be once per cmd? :)

**Comment by lugray** [comment]
That PR doesn't actually fix this one.

**Comment by burke** [comment]
Oh, yes, good point. Thanks.

**Comment by burke** [comment]
I think the answer here is:

* Get all errors passed up to `main.rs`
* On abort, pass the error to a handler function, which:
    * For certain types of errors (or all of them)?:
        * Designate a sentinel file (`.shadowenv.d/*`? `~/.config/...`? `/tmp/...`?)
        * Write some indication of the error, the path, and maybe the shell pid to this file
        * skip printing the error if that file exists and was created within some timeout

**Comment by lugray** [comment]
Given that you want the path as part of the info, `.shadowenv.d/...` makes the most sense to me.

**Comment by burke** [comment]
And I guess if there's no `.shadowenv.d`, we should be doing so little work that errors shouldn't happen.

**Comment by lugray** [comment]
> And I guess if there's no `.shadowenv.d`, we should be doing so little work that errors shouldn't happen.

And if they did, we should probably shut up about them because they're totally our fault 😆

**Comment by jules2689** [comment]
Why would the file be created within some timeout? Can you describe how the failure scenarios can occur?

**Comment by burke** [comment]
I'm using timeout to mean "duration" or "elapsed time" really. "was it created in the past X seconds"?
