### ISSUE TITLE
Don't allow subshells in values or names

### ISSUE THREAD

**Issue by burke** [Shopify/shadowenv#41]
A user has set `REVISION` to `"$(git ...)"`, which is kind of useful but:

a) better from a security standpoint to not allow this; and
b) it's shell-dependent.

Let's find a way to pass data to shells as literals.

**Comment by lavoiesl** [comment]
Note that for fish, variable interpolation is also different. `echo "${REVISION}"` is illegal, it has to be `echo "$REVISION"`.
