### ISSUE TITLE
[ Question ] Replace virtualenvs?

### ISSUE THREAD

**Issue by cig0** [Shopify/shadowenv#45]
So, it would be stupid to think that Shadowenv could allow me to replace my Python and Go virtualenvs? Thanks!

**Comment by lugray** [comment]
Do your virtualenvs do anything other than manipulate environment variables?  If so, then shadowenv could not replace them.  If not, then you could likely do it with shadowenv.  This is an example file I use in a go project:
`.shadowenv.d/580_dev_go.lisp`:
```lisp
(provide "go" "1.10.3")

(env/set "GO111MODULE" ())
(env/set "GOROOT" (path-concat (env/get "HOME") ".dev" "go" "1.10.3"))
(env/prepend-to-pathlist "PATH" (path-concat (env/get "GOROOT") "bin"))
```

**Comment by cig0** [comment]
Purrfect 👌Thank you Lisa.

**Comment by cig0** [comment]
Purrfect 👌Thank you Lisa.
