### ISSUE TITLE
Proposal: `shadowenv exec`

### ISSUE THREAD

**Issue by burke** [Shopify/shadowenv#46]
```
shadowenv exec -- nginx -g 'daemon off;'
shadowenv exec -d "${__shadowenv_data}" bash
```

Mostly useful when the shell shim isn't loaded, `shadowenv exec` would load the shadowenv from the current directory and `exec` the indicated command/process.

Here I've made `$__shadowenv_data` a flag rather than a positional argument, because I anticipate using this primarily in cases where Shadowenv is not loaded as a shell hook.

The first positional argument will be interpreted as the program, and extraneous arguments afterward will be an error.

Passing `--` as the first positional argument indicates that all subsequent arguments should be interpreted as the argv of the process to be exec'd.

## Example Use-Case

I'd like to be able to write out a `LaunchAgent` whose `ProgramArguments` would evaluate a Shadowenv without having to use `['bash', '-c', '...']`, e.g.:

```
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/shadowenv</string>
        <string>exec</string>
        <string>--</string>
        <string>myprogram</string>
        <string>--with-some-argument</string>
    </array>
    <key>WorkingDirectory</key>
    <string>/path/to/thing/with/env</string>
```

**Comment by lugray** [comment]
This would support a nice implementation #29 with simple wrapper script.

**Comment by burke** [comment]
I think it could be as simple as:

#### `file:bin/shadowenv-exec`
```
#!/bin/sh
shadowenv exec -- "$@"
```

**Comment by burke** [comment]
I'm going to take a run at this today.
