### ISSUE TITLE
Shadowenv lisp files are not sorted

### ISSUE THREAD

**Issue by lavoiesl** [Shopify/shadowenv#68]
The numbered prefix gives the impression that the last would take precedence.

Per documentation: https://doc.rust-lang.org/std/fs/fn.read_dir.html
>  // The order in which `read_dir` returns entries is not guaranteed. If reproducible
>  // ordering is required the entries should be explicitly sorted.

```
$ tail -n +1 .shadowenv.d/*.lisp
==> .shadowenv.d/000_test.lisp <==
(env/set "FOO" "BAR")

==> .shadowenv.d/100_test.lisp <==
(env/set "FOO" "BAZ")

==> .shadowenv.d/200_test.lisp <==
(env/set "FOO" "QUX")

$ echo $FOO
BAR
```

**Comment by burke** [comment]
Ah, I thought it was guaranteed on macOS at least so I was lazy about this. I'll make this change.
