### ISSUE TITLE
Reorganize `.shadowenv.d`:

### ISSUE THREAD

**Issue by burke** [Shopify/shadowenv#7]
The conversation on https://github.com/Shopify/shadowenv/issues/4 has me thinking a bit about how `.shadowenv.d` should be structured. I think maybe this makes sense:

```
.shadowenv.d
├── .error-1-12415
├── .gitignore
├── .trust-ab42714f
└── 500_default.scm
```

* `*.scm`: shadowlisp files
* `.trust-<fingerprint>`: trust files (now with a leading `.`)
* `.error-<n>-<pid>`: sentinel file for error `n` on pid `pid`, in this project.
* `.gitignore`: contains:

```
/.*
!/.gitignore
```

As a user, it feels more useful to see only the `*.scm` files.

**Comment by lugray** [comment]
- trust files => trust-file?  Do I misunderstand, or will a `.trust-*` be unique in `.shadowenv.d`?
- `pid` - I think this makes sense - it's the pid of a process started at shell start up, that stays active throughout a shell session?

**Comment by burke** [comment]
It's not necessarily unique in fringe cases, like two users collaborating on a single checkout over ssh or some weird situation like that. It's not common but it feels silly to make it so painful with a fairly trivial choice right now.

Yeah, the pid of the shell. I *should* just be able to use the parent pid.

**Comment by lugray** [comment]
This makes sense to me.
