### ISSUE TITLE
Expanding paths relative to the directory where the Shadowenv environment is defined

### ISSUE THREAD

**Issue by pepicrft** [Shopify/shadowenv#76]
👋 I'm using Shadowenv in a personal project, and I'd like to expose a path that is relative to the directory where the Shadowenv directory lives. Is that currently supported? If not, is this something that aligns with the project, and therefore I can contribute it myself? If so, I'd appreciate any pointers you can give me.

**Comment by lugray** [comment]
Do you mean like
```
$ which console
console not found
$ ls bin
console*  load.rb
$ echo '(env/prepend-to-pathlist "PATH" "./bin")' > .shadowenv.d/900_custom.lisp
activated shadowenv (ruby:2.5.1)
$ which console
./bin/console
```
?

**Comment by pepibumur** [comment]
Taking your example:

```
bin/
  console
.shadowenv.d/
  900_custom.lisp/ (contains '(env/prepend-to-pathlist "PATH" "./bin")')
subdirectory
```

Would I be able to run `console` when I'm in the `subdirectory`? I've tried and it doesn't work. I assume because the path is relative to the current directory. I was wondering if it makes sense to have a utility along the lines of:

```
(path-expand-from-root "bin")
```

Which concatenates bin to the directory that contains `.shadowenv.d`. That way, I would be able to call `console` from any subdirectory.

**Comment by lugray** [comment]
Ah, I see. I thought that made sense to include, so I started looking through [the shadowlisp docs](https://shopify.github.io/shadowenv/shadowlisp/) to get an idea of what would make a good function name and came across [expand-path](https://shopify.github.io/shadowenv/shadowlisp/#expand-path) which does the job:
```lisp
(env/prepend-to-pathlist "PATH" (expand-path "./bin"))
```

**Comment by pepibumur** [comment]
That worked! 🎉 What do you think if I extend the documentation to make it more clear that it can expand from the directory where the `.shadowenv.d` directory is contained?

**Comment by drdaeman** [comment]
Hey, may I ask to reopen this issue? I've just found out that `expand-path` is relative to the current working directory, not the project's root directory. So it depends on where you activate the environment from. If your shell jumps directly into a subdirectory of the project, you'll get an error:

    $ cd ~/Development/myproject/subdirectory
    I/O error: failed to read file `./.shadowenv.d/foorc`: No such file or directory (os error 2)
    
    Traceback:
    
      In main, function __shadowenv__500_default.lisp
    
    shadowenv failure: error while evaluating shadowlisp

I'd suggest either introducing a pre-defined variable like `env_root` that would always be the path to the directory where `.shadowenv.d` is located (so one can `(path-concat env_root ...)`), or introduce a new function like that proposed `path-expand-from-root`.
